import { randomUUID } from "node:crypto";
import { resolveCta } from "@/lib/commerce/cta";
import { getCommerceProvider } from "@/lib/commerce/provider";
import { getCatalog } from "@/lib/catalog";
import { siteUrl } from "@/lib/email";
import { getSiteMode } from "@/lib/mode";
import { nowIso, sha256 } from "@/lib/ops/crypto";
import { getStore } from "@/lib/store";
import type { Row } from "@/lib/store/types";

const refuse = (status: number, code: string, message: string) =>
  Response.json({ ok: false, code, message }, { status });

type OrderRow = Row & { checkout_session_id: string | null; status: string };

/**
 * Starts a Stripe Checkout session.
 *
 * Locked server-side: refused unless the site mode is "sale" AND the CTA
 * resolver answers "buy" for this pack and recipe. The Idempotency-Key header
 * (generated by the client per click) makes double submission return the
 * same session instead of creating a second order.
 */
export async function POST(request: Request) {
  if ((await getSiteMode()) !== "sale") {
    return refuse(403, "sales_closed", "La vente n'est pas ouverte.");
  }

  let body: { lines?: unknown };
  try {
    body = await request.json();
  } catch {
    return refuse(400, "bad_request", "Demande illisible.");
  }
  if (!Array.isArray(body.lines) || body.lines.length === 0 || body.lines.length > 10) {
    return refuse(422, "invalid_lines", "Le panier est vide ou invalide.");
  }

  /* Prices are recomputed here from the catalogue: the client sends keys only. */
  const catalog = await getCatalog();
  const resolved = [];
  for (const raw of body.lines as { packKey?: unknown; recipeKey?: unknown; quantity?: unknown }[]) {
    const pack = catalog.packs.find((p) => p.key === raw?.packKey);
    const recipe = catalog.recipes.find((r) => r.key === raw?.recipeKey);
    if (!pack || !recipe) return refuse(404, "not_found", "Un produit du panier est introuvable.");
    if (resolveCta("sale", pack, recipe, catalog.company).kind !== "buy") {
      return refuse(409, "not_purchasable", `« ${pack.name} ${recipe.name} » n'est pas disponible à l'achat.`);
    }
    const quantity = Number(raw.quantity ?? 1);
    if (!Number.isInteger(quantity) || quantity < 1 || quantity > 12) {
      return refuse(422, "invalid_quantity", "Quantité invalide (1 à 12).");
    }
    resolved.push({ pack, recipe, quantity, unit: Math.round((pack.price.value ?? 0) * 100) });
  }

  const idempotencyKey = request.headers.get("idempotency-key")?.trim();
  if (!idempotencyKey) return refuse(400, "idempotency_key_required", "Idempotency-Key requise.");

  const provider = getCommerceProvider();
  const store = getStore();
  if (!provider.configured || !store) {
    return refuse(503, "payment_not_configured", "Le paiement n'est pas disponible pour le moment.");
  }

  const orderId = `ord_${sha256(idempotencyKey).slice(0, 24)}`;
  const existing = await store.get<OrderRow>("orders", orderId);
  if (existing?.checkout_session_id) {
    const session = await provider.getCheckoutSession(existing.checkout_session_id);
    if (session.status === "open" && session.url) return Response.json({ ok: true, url: session.url });
    return refuse(409, "already_processed", "Cette commande a déjà été traitée.");
  }

  const base = siteUrl();
  try {
    if (!existing) {
      await store.insert("orders", {
        id: orderId,
        status: "pending",
        email: null,
        lines: resolved.map((l) => ({
          packKey: l.pack.key,
          recipeKey: l.recipe.key,
          quantity: l.quantity,
          unitAmountCents: l.unit,
          doses: l.pack.doses * l.quantity,
        })),
        amount_total_cents: resolved.reduce((s, l) => s + l.unit * l.quantity, 0),
        currency: "eur",
        checkout_session_id: null,
        payment_intent_id: null,
        created_at: nowIso(),
        paid_at: null,
        updated_at: nowIso(),
      });
    }
    const session = await provider.createCheckout({
      lines: resolved.map((l) => ({
        packKey: l.pack.key,
        name: `Matocha ${l.pack.name} — ${l.recipe.name} (${l.pack.doses} doses)`,
        unitAmountCents: l.unit,
        quantity: l.quantity,
      })),
      successUrl: `${base}/commande/merci?session_id={CHECKOUT_SESSION_ID}`,
      cancelUrl: `${base}/commande/annulee`,
      idempotencyKey: `checkout-${orderId}`,
      metadata: { order_id: orderId, attempt: randomUUID() },
    });
    await store.update("orders", orderId, { checkout_session_id: session.id, updated_at: nowIso() });
    return Response.json({ ok: true, url: session.url });
  } catch (error) {
    console.error("[checkout] failed", error);
    return refuse(502, "checkout_failed", "Le paiement n'a pas pu démarrer. Réessayez.");
  }
}
